In [1]:
import pandas as pd

df = pd.read_pickle("shelter_data.pkl")

In [2]:
df.head()

,Animal ID,Name,DateTime_in,Found Location,Intake Type,Intake Condition,Breed,Color,Month_in,Year_in,...,Month_out,Year_out,Age upon Outcome (months),DateTime_out,Number of Outcome,Outcome Type,Outcome Subtype,Status_out,Sex_out,Time in shelter
0,A006100,Scamp,2014-03-07 14:26:00,8700 Research in Austin (TX),Public Assist,Normal,Spinone Italiano Mix,Yellow/White,3,2014,...,3.0,2014.0,72,2014-03-08 17:10:00,1,Return to Owner,NaN,Neutered,Male,1 days 02:44:00
1,A006100,Scamp,2014-12-19 10:21:00,8700 Research Blvd in Austin (TX),Public Assist,Normal,Spinone Italiano Mix,Yellow/White,12,2014,...,12.0,2014.0,84,2014-12-20 16:35:00,2,Return to Owner,NaN,Neutered,Male,1 days 06:14:00
2,A006100,Scamp,2017-12-07 14:07:00,Colony Creek And Hunters Trace in Austin (TX),Stray,Normal,Spinone Italiano Mix,Yellow/White,12,2017,...,12.0,2017.0,120,2017-12-07 00:00:00,3,Return to Owner,NaN,Neutered,Male,0 days 05:00:00
3,A047759,Oreo,2014-04-02 15:55:00,Austin (TX),Owner Surrender,Normal,Dachshund,Tricolor,4,2014,...,4.0,2014.0,120,2014-04-07 15:12:00,1,Transfer,Partner,Neutered,Male,4 days 23:17:00
4,A134067,Bandit,2013-11-16 09:02:00,12034 Research Blvd in Austin (TX),Public Assist,Injured,Shetland Sheepdog,Brown/White,11,2013,...,11.0,2013.0,192,2013-11-16 11:54:00,1,Return to Owner,NaN,Neutered,Male,0 days 02:52:00

In [3]:
def getOverview(df):
    '''Returns summary about the data in the dataframe.

        Creates a dataFrame with datatypes, unique, nunique, number of missing values; 
               
        Args:
            df (pandas.dataFrame): a dataframe with rows and columns

        Returns:
            None
    '''
    df = df.copy()
    display(pd.DataFrame({'dtype': df.dtypes,                                   # Dtypes
                          'total': df.count(),                                  # number of valid entries
                          'missing_n': df.isna().sum(),                         # Number nan-entries
                          'missing_%': df.isna().mean()*100,                    # Ratio of missing values in %
                          'uniques_n': df.nunique(),                            # Caridinality (Number of unique values)
                          'uniques': [df[col].unique() for col in df.columns]   # List of unique values
                         }))
pd.set_option("display.float_format", "{:,.2f}".format)

In [4]:
getOverview(df)

,dtype,total,missing_n,missing_%,uniques_n,uniques
Animal ID,str,87176,0,0.00,73783,"[A006100, A047759, A134067, A141142, A163459, ..."
Name,str,73411,13765,15.79,17980,"[Scamp, Oreo, Bandit, Bettie, Sasha, Pep, Boti..."
DateTime_in,datetime64[us],87176,0,0.00,68727,"[2014-03-07 14:26:00, 2014-12-19 10:21:00, 201..."
Found Location,str,87176,0,0.00,41624,"[8700 Research in Austin (TX), 8700 Research B..."
Intake Type,str,87176,0,0.00,6,"[Public Assist, Stray, Owner Surrender, Euthan..."
Intake Condition,str,87176,0,0.00,18,"[Normal, Injured, Aged, Sick, Medical, Other, ..."
Breed,str,87176,0,0.00,2554,"[Spinone Italiano Mix, Dachshund, Shetland She..."
Color,str,87176,0,0.00,392,"[Yellow/White, Tricolor, Brown/White, Black/Wh..."
Month_in,int32,87176,0,0.00,12,"[3, 12, 4, 11, 9, 10, 2, 8, 7, 6, 5, 1]"
Year_in,int32,87176,0,0.00,11,"[2014, 2017, 2013, 2015, 2016, 2018, 2019, 202..."
Age upon Intake (months),Int64,87175,1,0.00,34,"[72, 84, 120, 192, 180, 216, 168, 204, 156, 14..."
Number of Intake,Int64,87176,0,0.00,33,"[1, 2, 3, 5, 4, 6, 7, 8, 9, 10, 11, 13, 12, 14..."
Left,bool,87176,0,0.00,2,"[True, False]"
Status_in,str,87176,0,0.00,5,"[Neutered, Spayed, Intact, Unknown, Missing]"
Sex_in,str,87176,0,0.00,3,"[Male, Female, Missing]"
Month_out,float64,86623,553,0.63,12,"[3.0, 12.0, 4.0, 11.0, 9.0, 2.0, 10.0, 8.0, 7...."
Year_out,float64,86623,553,0.63,11,"[2014.0, 2017.0, 2013.0, 2015.0, 2016.0, 2018...."
Age upon Outcome (months),Int64,86621,555,0.64,34,"[72, 84, 120, 192, 180, 216, 168, 204, 156, 14..."
DateTime_out,datetime64[us],86623,553,0.63,77668,"[2014-03-08 17:10:00, 2014-12-20 16:35:00, 201..."
Number of Outcome,int64,87176,0,0.00,34,"[1, 2, 3, 4, 5, 6, 0, 7, 8, 9, 10, 11, 14, 12,..."
Outcome Type,str,86606,570,0.65,9,"[Return to Owner, Transfer, Adoption, Euthanas..."
Outcome Subtype,str,28588,58588,67.21,24,"[nan, Partner, Foster, Suffering, Medical, Beh..."
Status_out,str,86623,553,0.63,5,"[Neutered, Spayed, Intact, nan, Unknown, Missing]"
Sex_out,str,86623,553,0.63,3,"[Male, Female, nan, Missing]"
Time in shelter,timedelta64[us],80365,6811,7.81,34902,"[1 days 02:44:00, 1 days 06:14:00, 0 days 05:0..."